/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;

/**
 *
 * @author Nemanja
 */
public class FDodajNosnju extends javax.swing.JDialog {

    /**
     * Creates new form FDodajNosnju
     */
    public FDodajNosnju(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtSifraNosnje = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPol = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxKolicina = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtOpisNosnje = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTxtNazivNosnje = new javax.swing.JTextField();
        jLabgreskaNaziv = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxVrstaNosnje = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxVelicina = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxVrstaOpanaka = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jComboBoxVrstaBeline = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBtnCancel = new javax.swing.JButton();
        jBtnEnableChanges = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jBtnUbaciNovog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 197, 107));
        jLabel1.setText("Sifra nosnje:");

        jTxtSifraNosnje.setBackground(new java.awt.Color(51, 51, 51));
        jTxtSifraNosnje.setForeground(new java.awt.Color(223, 171, 73));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 197, 107));
        jLabel3.setText("Pol:");

        jComboBoxPol.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxPol.setForeground(new java.awt.Color(213, 177, 82));

        jLabel7.setText(" ");

        jLabel9.setText(" ");

        jLabel11.setText(" ");

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(223, 197, 107));
        jLabel12.setText("Kolicina:");

        jComboBoxKolicina.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxKolicina.setForeground(new java.awt.Color(213, 177, 82));

        jLabel13.setText(" ");

        jTxtOpisNosnje.setBackground(new java.awt.Color(51, 51, 51));
        jTxtOpisNosnje.setColumns(20);
        jTxtOpisNosnje.setForeground(new java.awt.Color(213, 177, 82));
        jTxtOpisNosnje.setRows(5);
        jScrollPane1.setViewportView(jTxtOpisNosnje);

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(223, 197, 107));
        jLabel14.setText("Opis nosnje:");

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(223, 197, 107));
        jLabel15.setText("Naziv nosnje:");

        jTxtNazivNosnje.setBackground(new java.awt.Color(51, 51, 51));
        jTxtNazivNosnje.setForeground(new java.awt.Color(213, 177, 82));

        jLabgreskaNaziv.setForeground(new java.awt.Color(153, 0, 0));
        jLabgreskaNaziv.setText(" ");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(223, 197, 107));
        jLabel6.setText("Vrsta nosnje:");

        jComboBoxVrstaNosnje.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxVrstaNosnje.setForeground(new java.awt.Color(213, 177, 82));
        jComboBoxVrstaNosnje.setBorder(null);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opanci", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(223, 197, 107));
        jLabel8.setText("Velicina opanaka:");

        jComboBoxVelicina.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxVelicina.setForeground(new java.awt.Color(213, 177, 82));

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(223, 197, 107));
        jLabel10.setText("Vrsta opanaka:");

        jComboBoxVrstaOpanaka.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxVrstaOpanaka.setForeground(new java.awt.Color(213, 177, 82));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxVelicina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jComboBoxVrstaOpanaka, 0, 133, Short.MAX_VALUE)
                            .addGap(128, 128, 128)))
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jComboBoxVelicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBoxVrstaOpanaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Belina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N

        jComboBoxVrstaBeline.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxVrstaBeline.setForeground(new java.awt.Color(213, 177, 82));

        jLabel17.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(223, 197, 107));
        jLabel17.setText("Vrsta beline:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel17)
                    .addGap(18, 18, 18)
                    .addComponent(jComboBoxVrstaBeline, 0, 287, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBoxVrstaBeline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(42, 42, 42)
                                .addComponent(jComboBoxKolicina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxVrstaNosnje, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(24, 24, 24)
                                    .addComponent(jTxtSifraNosnje, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(jLabgreskaNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTxtNazivNosnje, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jComboBoxPol, 0, 305, Short.MAX_VALUE)))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(306, 306, 306)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxVrstaNosnje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtSifraNosnje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTxtNazivNosnje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabgreskaNaziv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBoxKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(116, 116, 116)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel9)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 181, 107)));

        jBtnCancel.setBackground(new java.awt.Color(51, 51, 51));
        jBtnCancel.setForeground(new java.awt.Color(223, 181, 107));
        jBtnCancel.setText("Izađi");
        jBtnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 181, 107), 2, true));
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jBtnEnableChanges.setBackground(new java.awt.Color(223, 181, 107));
        jBtnEnableChanges.setText("Omogući promene");
        jBtnEnableChanges.setBorder(null);
        jBtnEnableChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnableChangesActionPerformed(evt);
            }
        });

        jBtnDelete.setBackground(new java.awt.Color(223, 181, 107));
        jBtnDelete.setText("Izbriši");
        jBtnDelete.setBorder(null);
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnUpdate.setBackground(new java.awt.Color(223, 181, 107));
        jBtnUpdate.setText("Ažuriraj");
        jBtnUpdate.setBorder(null);
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnSave.setBackground(new java.awt.Color(223, 181, 107));
        jBtnSave.setForeground(new java.awt.Color(51, 51, 51));
        jBtnSave.setText("Sačuvaj");
        jBtnSave.setBorder(null);
        jBtnSave.setBorderPainted(false);
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jBtnUbaciNovog.setBackground(new java.awt.Color(223, 181, 107));
        jBtnUbaciNovog.setText("Ubaci novu nošnju");
        jBtnUbaciNovog.setBorder(null);
        jBtnUbaciNovog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUbaciNovogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnUbaciNovog, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jBtnEnableChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEnableChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnUbaciNovog, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnEnableChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnableChangesActionPerformed

    }//GEN-LAST:event_jBtnEnableChangesActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed

    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed

    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed

    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnUbaciNovogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUbaciNovogActionPerformed

    }//GEN-LAST:event_jBtnUbaciNovogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnEnableChanges;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnUbaciNovog;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JComboBox<Integer> jComboBoxKolicina;
    private javax.swing.JComboBox<domain.enumeracije.Pol> jComboBoxPol;
    private javax.swing.JComboBox<String> jComboBoxVelicina;
    private javax.swing.JComboBox<String> jComboBoxVrstaBeline;
    private javax.swing.JComboBox<domain.enumeracije.VrstaNosnje> jComboBoxVrstaNosnje;
    private javax.swing.JComboBox<String> jComboBoxVrstaOpanaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabgreskaNaziv;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtNazivNosnje;
    private javax.swing.JTextArea jTxtOpisNosnje;
    private javax.swing.JTextField jTxtSifraNosnje;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void addVrstaNosnjeItemStateChanged(ItemListener ae){
        jComboBoxVrstaNosnje.addItemListener(ae);
    }
    
    public void addButtonSaveListener(ActionListener ae){
        jBtnSave.addActionListener(ae);
    }
    
    public void addButtonUpdateListener(ActionListener ae){
        jBtnUpdate.addActionListener(ae);
    }
    public void addButtonDeleteListener(ActionListener ae){
        jBtnDelete.addActionListener(ae);
    }
    
    public void addButtonEnableChangesListener(ActionListener ae){
        jBtnEnableChanges.addActionListener(ae);
    }
    
    public void addButtonUbaciNovogListener(ActionListener ae){
        jBtnUbaciNovog.addActionListener(ae);
    }
    
    public void addButtonCancelListener(ActionListener ae){
        jBtnCancel.addActionListener(ae);
    }

    public javax.swing.JButton getjBtnCancel() {
        return jBtnCancel;
    }

    public void setjBtnCancel(javax.swing.JButton jBtnCancel) {
        this.jBtnCancel = jBtnCancel;
    }

    public javax.swing.JButton getjBtnDelete() {
        return jBtnDelete;
    }

    public void setjBtnDelete(javax.swing.JButton jBtnDelete) {
        this.jBtnDelete = jBtnDelete;
    }

    public javax.swing.JButton getjBtnEnableChanges() {
        return jBtnEnableChanges;
    }

    public void setjBtnEnableChanges(javax.swing.JButton jBtnEnableChanges) {
        this.jBtnEnableChanges = jBtnEnableChanges;
    }

    public javax.swing.JButton getjBtnSave() {
        return jBtnSave;
    }

    public void setjBtnSave(javax.swing.JButton jBtnSave) {
        this.jBtnSave = jBtnSave;
    }

    public javax.swing.JButton getjBtnUbaciNovog() {
        return jBtnUbaciNovog;
    }

    public void setjBtnUbaciNovog(javax.swing.JButton jBtnUbaciNovog) {
        this.jBtnUbaciNovog = jBtnUbaciNovog;
    }

    public javax.swing.JButton getjBtnUpdate() {
        return jBtnUpdate;
    }

    public void setjBtnUpdate(javax.swing.JButton jBtnUpdate) {
        this.jBtnUpdate = jBtnUpdate;
    }

    public javax.swing.JComboBox<Integer> getjComboBoxKolicina() {
        return jComboBoxKolicina;
    }

    public void setjComboBoxKolicina(javax.swing.JComboBox<Integer> jComboBoxKolicina) {
        this.jComboBoxKolicina = jComboBoxKolicina;
    }

    public javax.swing.JComboBox<domain.enumeracije.Pol> getjComboBoxPol() {
        return jComboBoxPol;
    }

    public void setjComboBoxPol(javax.swing.JComboBox<domain.enumeracije.Pol> jComboBoxPol) {
        this.jComboBoxPol = jComboBoxPol;
    }

    

    

    public javax.swing.JComboBox<domain.enumeracije.VrstaNosnje> getjComboBoxVrstaNosnje() {
        return jComboBoxVrstaNosnje;
    }

    public void setjComboBoxVrstaNosnje(javax.swing.JComboBox<domain.enumeracije.VrstaNosnje> jComboBoxVrstaNosnje) {
        this.jComboBoxVrstaNosnje = jComboBoxVrstaNosnje;
    }

    

    public javax.swing.JTextField getjTxtNazivNosnje() {
        return jTxtNazivNosnje;
    }

    public void setjTxtNazivNosnje(javax.swing.JTextField jTxtNazivNosnje) {
        this.jTxtNazivNosnje = jTxtNazivNosnje;
    }

    public javax.swing.JTextArea getjTxtOpisNosnje() {
        return jTxtOpisNosnje;
    }

    public void setjTxtOpisNosnje(javax.swing.JTextArea jTxtOpisNosnje) {
        this.jTxtOpisNosnje = jTxtOpisNosnje;
    }

    public javax.swing.JTextField getjTxtSifraNosnje() {
        return jTxtSifraNosnje;
    }

    public void setjTxtSifraNosnje(javax.swing.JTextField jTxtSifraNosnje) {
        this.jTxtSifraNosnje = jTxtSifraNosnje;
    }

    public javax.swing.JComboBox<String> getjComboBoxVelicina() {
        return jComboBoxVelicina;
    }

    public void setjComboBoxVelicina(javax.swing.JComboBox<String> jComboBoxVelicina) {
        this.jComboBoxVelicina = jComboBoxVelicina;
    }

    public javax.swing.JComboBox<String> getjComboBoxVrstaBeline() {
        return jComboBoxVrstaBeline;
    }

    public void setjComboBoxVrstaBeline(javax.swing.JComboBox<String> jComboBoxVrstaBeline) {
        this.jComboBoxVrstaBeline = jComboBoxVrstaBeline;
    }

    public javax.swing.JComboBox<String> getjComboBoxVrstaOpanaka() {
        return jComboBoxVrstaOpanaka;
    }

    public void setjComboBoxVrstaOpanaka(javax.swing.JComboBox<String> jComboBoxVrstaOpanaka) {
        this.jComboBoxVrstaOpanaka = jComboBoxVrstaOpanaka;
    }

    public javax.swing.JLabel getjLabgreskaNaziv() {
        return jLabgreskaNaziv;
    }

    public void setjLabgreskaNaziv(javax.swing.JLabel jLabgreskaNaziv) {
        this.jLabgreskaNaziv = jLabgreskaNaziv;
    }

    
    
    
}
