/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Nemanja
 */
public class FLogin extends javax.swing.JFrame {

    /**
     * Creates new form FLogin
     */
    public FLogin() {
        initComponents();
        setLocationRelativeTo(null);  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabUsername = new javax.swing.JLabel();
        jTxtUsername = new javax.swing.JTextField();
        jLabPassword = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        jBtnIzadji = new javax.swing.JButton();
        jBtnLogin = new javax.swing.JButton();
        jLabUsernameError = new javax.swing.JLabel();
        jLabPasswordError = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Optimized-Za Kontica-page-001 (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prijavi se:");

        jLabUsername.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabUsername.setText("Username:");

        jTxtUsername.setBackground(new java.awt.Color(51, 51, 51));
        jTxtUsername.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jTxtUsername.setForeground(new java.awt.Color(255, 255, 255));
        jTxtUsername.setBorder(null);
        jTxtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabPassword.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabPassword.setText("Password:");

        jTxtPassword.setBackground(new java.awt.Color(51, 51, 51));
        jTxtPassword.setForeground(new java.awt.Color(255, 255, 255));
        jTxtPassword.setBorder(null);

        jBtnIzadji.setBackground(new java.awt.Color(255, 255, 255));
        jBtnIzadji.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jBtnIzadji.setForeground(new java.awt.Color(51, 51, 51));
        jBtnIzadji.setText("IZADJI");
        jBtnIzadji.setBorder(null);
        jBtnIzadji.setBorderPainted(false);
        jBtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzadjiActionPerformed(evt);
            }
        });

        jBtnLogin.setBackground(new java.awt.Color(223, 181, 107));
        jBtnLogin.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jBtnLogin.setText("PRIJAVI SE");
        jBtnLogin.setBorderPainted(false);
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });

        jLabUsernameError.setBackground(new java.awt.Color(51, 51, 51));
        jLabUsernameError.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabUsernameError.setForeground(new java.awt.Color(153, 0, 0));
        jLabUsernameError.setText(" ");

        jLabPasswordError.setBackground(new java.awt.Color(51, 51, 51));
        jLabPasswordError.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabPasswordError.setForeground(new java.awt.Color(153, 0, 0));
        jLabPasswordError.setText(" ");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabUsername)
                        .addGap(4, 4, 4)
                        .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabUsernameError, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabPassword)
                        .addGap(8, 8, 8)
                        .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabPasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabUsername))
                    .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabUsernameError))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabPassword))
                    .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabPasswordError))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzadjiActionPerformed
        
    }//GEN-LAST:event_jBtnIzadjiActionPerformed

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        
    }//GEN-LAST:event_jBtnLoginActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIzadji;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabPassword;
    private javax.swing.JLabel jLabPasswordError;
    private javax.swing.JLabel jLabUsername;
    private javax.swing.JLabel jLabUsernameError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JTextField jTxtUsername;
    // End of variables declaration//GEN-END:variables

    public void addButtonLoginListener(ActionListener ae){
        jBtnLogin.addActionListener(ae);
    }
    
    public void addButtonCancelListener(ActionListener ae){
        jBtnIzadji.addActionListener(ae);
    }

    public javax.swing.JButton getjBtnIzadji() {
        return jBtnIzadji;
    }

    public void setjBtnIzadji(javax.swing.JButton jBtnIzadji) {
        this.jBtnIzadji = jBtnIzadji;
    }

    public javax.swing.JButton getjBtnLogin() {
        return jBtnLogin;
    }

    public void setjBtnLogin(javax.swing.JButton jBtnLogin) {
        this.jBtnLogin = jBtnLogin;
    }

    public javax.swing.JLabel getjLabPassword() {
        return jLabPassword;
    }

    public void setjLabPassword(javax.swing.JLabel jLabPassword) {
        this.jLabPassword = jLabPassword;
    }

    public javax.swing.JLabel getjLabPasswordError() {
        return jLabPasswordError;
    }

    public void setjLabPasswordError(javax.swing.JLabel jLabPasswordError) {
        this.jLabPasswordError = jLabPasswordError;
    }

    public javax.swing.JLabel getjLabUsername() {
        return jLabUsername;
    }

    public void setjLabUsername(javax.swing.JLabel jLabUsername) {
        this.jLabUsername = jLabUsername;
    }

    public javax.swing.JLabel getjLabUsernameError() {
        return jLabUsernameError;
    }

    public void setjLabUsernameError(javax.swing.JLabel jLabUsernameError) {
        this.jLabUsernameError = jLabUsernameError;
    }

    public javax.swing.JPasswordField getjTxtPassword() {
        return jTxtPassword;
    }

    public void setjTxtPassword(javax.swing.JPasswordField jTxtPassword) {
        this.jTxtPassword = jTxtPassword;
    }

    public javax.swing.JTextField getjTxtUsername() {
        return jTxtUsername;
    }

    public void setjTxtUsername(javax.swing.JTextField jTxtUsername) {
        this.jTxtUsername = jTxtUsername;
    }
    
    
    
}
