/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import domain.enumeracije.FormMode;
import java.awt.event.ActionListener;

/**
 *
 * @author Nemanja
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrviAnsambl = new javax.swing.JMenu();
        jMenuClanovi = new javax.swing.JMenu();
        jMenuItemNoviClan = new javax.swing.JMenuItem();
        jMenuItemPretraga = new javax.swing.JMenuItem();
        jMenuEkonomat = new javax.swing.JMenu();
        jMenuItemDodajNosnju = new javax.swing.JMenuItem();
        jMenuItemPrikazNosnje = new javax.swing.JMenuItem();
        jMenuItemIzdavanjeNosnje = new javax.swing.JMenuItem();
        jMenuItemPretragaOtpremnice = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dobrodosli!");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Optimized-Za Kontica-page-001 (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(223, 197, 107));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(148, 50));

        jMenuPrviAnsambl.setBackground(new java.awt.Color(51, 51, 51));
        jMenuPrviAnsambl.setBorder(null);
        jMenuPrviAnsambl.setForeground(new java.awt.Color(223, 197, 107));
        jMenuPrviAnsambl.setText(" Ansambl");
        jMenuPrviAnsambl.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jMenuPrviAnsambl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuPrviAnsambl.setOpaque(true);
        jMenuPrviAnsambl.setPreferredSize(new java.awt.Dimension(140, 30));

        jMenuClanovi.setBackground(new java.awt.Color(51, 51, 51));
        jMenuClanovi.setBorder(null);
        jMenuClanovi.setForeground(new java.awt.Color(223, 200, 77));
        jMenuClanovi.setText("Clanovi");
        jMenuClanovi.setContentAreaFilled(true);
        jMenuClanovi.setPreferredSize(new java.awt.Dimension(150, 30));

        jMenuItemNoviClan.setText("Novi clan");
        jMenuItemNoviClan.setBorder(null);
        jMenuItemNoviClan.setContentAreaFilled(false);
        jMenuItemNoviClan.setPreferredSize(new java.awt.Dimension(120, 50));
        jMenuItemNoviClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNoviClanActionPerformed(evt);
            }
        });
        jMenuClanovi.add(jMenuItemNoviClan);

        jMenuItemPretraga.setText("Pretraga clanova");
        jMenuItemPretraga.setPreferredSize(new java.awt.Dimension(120, 50));
        jMenuItemPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretragaActionPerformed(evt);
            }
        });
        jMenuClanovi.add(jMenuItemPretraga);

        jMenuPrviAnsambl.add(jMenuClanovi);

        jMenuBar1.add(jMenuPrviAnsambl);
        jMenuPrviAnsambl.getAccessibleContext().setAccessibleDescription("");

        jMenuEkonomat.setBackground(new java.awt.Color(51, 51, 51));
        jMenuEkonomat.setBorder(null);
        jMenuEkonomat.setForeground(new java.awt.Color(223, 197, 107));
        jMenuEkonomat.setText("Ekonomat");
        jMenuEkonomat.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N

        jMenuItemDodajNosnju.setText("Dodaj nosnju");
        jMenuItemDodajNosnju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajNosnjuActionPerformed(evt);
            }
        });
        jMenuEkonomat.add(jMenuItemDodajNosnju);

        jMenuItemPrikazNosnje.setText("Prikaz nosnje");
        jMenuItemPrikazNosnje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazNosnjeActionPerformed(evt);
            }
        });
        jMenuEkonomat.add(jMenuItemPrikazNosnje);

        jMenuItemIzdavanjeNosnje.setText("Izdavanje nosnje");
        jMenuItemIzdavanjeNosnje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIzdavanjeNosnjeActionPerformed(evt);
            }
        });
        jMenuEkonomat.add(jMenuItemIzdavanjeNosnje);

        jMenuItemPretragaOtpremnice.setText("Pretraga otpremnica");
        jMenuEkonomat.add(jMenuItemPretragaOtpremnice);

        jMenuBar1.add(jMenuEkonomat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNoviClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNoviClanActionPerformed
        
    }//GEN-LAST:event_jMenuItemNoviClanActionPerformed

    private void jMenuItemPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretragaActionPerformed
        
    }//GEN-LAST:event_jMenuItemPretragaActionPerformed

    private void jMenuItemDodajNosnjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajNosnjuActionPerformed
       
    }//GEN-LAST:event_jMenuItemDodajNosnjuActionPerformed

    private void jMenuItemPrikazNosnjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazNosnjeActionPerformed
        
    }//GEN-LAST:event_jMenuItemPrikazNosnjeActionPerformed

    private void jMenuItemIzdavanjeNosnjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIzdavanjeNosnjeActionPerformed
       
    }//GEN-LAST:event_jMenuItemIzdavanjeNosnjeActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClanovi;
    private javax.swing.JMenu jMenuEkonomat;
    private javax.swing.JMenuItem jMenuItemDodajNosnju;
    private javax.swing.JMenuItem jMenuItemIzdavanjeNosnje;
    private javax.swing.JMenuItem jMenuItemNoviClan;
    private javax.swing.JMenuItem jMenuItemPretraga;
    private javax.swing.JMenuItem jMenuItemPretragaOtpremnice;
    private javax.swing.JMenuItem jMenuItemPrikazNosnje;
    private javax.swing.JMenu jMenuPrviAnsambl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void addButtonNoviClanListener(ActionListener ae){
        jMenuItemNoviClan.addActionListener(ae);
    }

    public void addButtonPretragaClanovaListener(ActionListener ae){
        jMenuItemPretraga.addActionListener(ae);
    }
    
    public void addButtonDodajNosnjuListener(ActionListener ae){
        jMenuItemDodajNosnju.addActionListener(ae);
    }
    
    public void addButtonPretragaNosnjeListener(ActionListener ae){
        jMenuItemPrikazNosnje.addActionListener(ae);
    }
    
    public void addButtonIzdavanjeNosnjeListener(ActionListener ae){
        jMenuItemIzdavanjeNosnje.addActionListener(ae);
    }
    
    public void addButtonPretragaOtpremnicaListener(ActionListener ae){
        jMenuItemPretragaOtpremnice.addActionListener(ae);
    }
    
}
