/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import domain.Clan;
import domain.enumeracije.Ansambl;
import domain.enumeracije.FormMode;
import domain.enumeracije.Pol;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import ui.component.table.model.ClanTableModel;



/**
 *
 * @author Nemanja
 */
public class FNoviClan extends javax.swing.JDialog {
    
    /**
     * Creates new form FNoviClan
     */
   
    
    
    

    public FNoviClan(FMain form, boolean modal/*, FormMode form_mode*/) {
        super(form, modal);
        initComponents();
        setLocationRelativeTo(null);
        jComboBoxPol.setForeground(new Color(223,197,107));
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtnCancel = new javax.swing.JButton();
        jBtnEnableChanges = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jBtnUbaciNovog = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtBrojCK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtIme = new javax.swing.JTextField();
        jlaberrorIme = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtPrezime = new javax.swing.JTextField();
        jlabErrorPrezime = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxPol = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxDan = new javax.swing.JComboBox<>();
        jComboBoxMesec = new javax.swing.JComboBox<>();
        jComboBoxGodina = new javax.swing.JComboBox<>();
        jComboBoxDan1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxMesec1 = new javax.swing.JComboBox<>();
        jComboBoxGodina1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxAnsambl = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxAktivan = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxVisina = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxBrojObuce = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(223, 197, 107), new java.awt.Color(223, 197, 107), new java.awt.Color(162, 112, 47), new java.awt.Color(162, 112, 47)));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jBtnCancel.setBackground(new java.awt.Color(223, 181, 107));
        jBtnCancel.setText("Izađi");
        jBtnCancel.setBorder(null);
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jBtnEnableChanges.setBackground(new java.awt.Color(223, 181, 107));
        jBtnEnableChanges.setText("Omogući promene");
        jBtnEnableChanges.setBorder(null);
        jBtnEnableChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnableChangesActionPerformed(evt);
            }
        });

        jBtnDelete.setBackground(new java.awt.Color(223, 181, 107));
        jBtnDelete.setText("Izbriši");
        jBtnDelete.setBorder(null);
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnUpdate.setBackground(new java.awt.Color(223, 181, 107));
        jBtnUpdate.setText("Ažuriraj");
        jBtnUpdate.setBorder(null);
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnSave.setBackground(new java.awt.Color(223, 181, 107));
        jBtnSave.setForeground(new java.awt.Color(51, 51, 51));
        jBtnSave.setText("Sačuvaj");
        jBtnSave.setBorder(null);
        jBtnSave.setBorderPainted(false);
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jBtnUbaciNovog.setBackground(new java.awt.Color(223, 181, 107));
        jBtnUbaciNovog.setText("Ubaci novog");
        jBtnUbaciNovog.setBorder(null);
        jBtnUbaciNovog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUbaciNovogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnUbaciNovog, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jBtnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnEnableChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jBtnUbaciNovog, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnEnableChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(325, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(223, 197, 107));

        jLabel1.setForeground(new java.awt.Color(223, 197, 107));
        jLabel1.setText("Broj clanske karte:");

        jTxtBrojCK.setEditable(false);
        jTxtBrojCK.setBackground(new java.awt.Color(51, 51, 51));
        jTxtBrojCK.setForeground(new java.awt.Color(223, 197, 107));
        jTxtBrojCK.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText(" ");

        jLabel3.setForeground(new java.awt.Color(223, 197, 107));
        jLabel3.setText("Ime:");

        jTxtIme.setBackground(new java.awt.Color(51, 51, 51));
        jTxtIme.setForeground(new java.awt.Color(223, 197, 107));
        jTxtIme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N

        jlaberrorIme.setForeground(new java.awt.Color(204, 0, 0));
        jlaberrorIme.setText(" ");

        jLabel5.setForeground(new java.awt.Color(223, 197, 107));
        jLabel5.setText("Prezime:");

        jTxtPrezime.setBackground(new java.awt.Color(51, 51, 51));
        jTxtPrezime.setForeground(new java.awt.Color(223, 197, 107));
        jTxtPrezime.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlabErrorPrezime.setForeground(new java.awt.Color(204, 0, 0));
        jlabErrorPrezime.setText(" ");

        jLabel7.setForeground(new java.awt.Color(223, 197, 107));
        jLabel7.setText("Pol:");

        jLabel8.setText(" ");

        jLabel9.setForeground(new java.awt.Color(223, 197, 107));
        jLabel9.setText("Visina:");

        jLabel10.setText(" ");

        jComboBoxPol.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxPol.setForeground(new java.awt.Color(223, 181, 107));

        jLabel11.setForeground(new java.awt.Color(223, 197, 107));
        jLabel11.setText("Datum rodjenja:");

        jLabel12.setText(" ");

        jComboBoxDan.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxDan.setForeground(new java.awt.Color(223, 181, 107));

        jComboBoxMesec.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxMesec.setForeground(new java.awt.Color(223, 181, 107));

        jComboBoxGodina.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxGodina.setForeground(new java.awt.Color(223, 181, 107));

        jComboBoxDan1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxDan1.setForeground(new java.awt.Color(223, 181, 107));

        jLabel13.setForeground(new java.awt.Color(223, 197, 107));
        jLabel13.setText("Datum uclanjenja:");

        jComboBoxMesec1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxMesec1.setForeground(new java.awt.Color(223, 181, 107));

        jComboBoxGodina1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxGodina1.setForeground(new java.awt.Color(223, 181, 107));

        jLabel14.setText(" ");

        jLabel15.setForeground(new java.awt.Color(223, 197, 107));
        jLabel15.setText("Broj obuce:");

        jLabel16.setText(" ");

        jLabel17.setForeground(new java.awt.Color(223, 197, 107));
        jLabel17.setText("Ansambl:");

        jLabel18.setText(" ");

        jComboBoxAnsambl.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxAnsambl.setForeground(new java.awt.Color(223, 181, 107));

        jLabel19.setForeground(new java.awt.Color(223, 197, 107));
        jLabel19.setText("Aktivan:");

        jComboBoxAktivan.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxAktivan.setForeground(new java.awt.Color(223, 181, 107));
        jComboBoxAktivan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setText(" ");

        jComboBoxVisina.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxVisina.setForeground(new java.awt.Color(223, 181, 107));

        jLabel21.setForeground(new java.awt.Color(223, 197, 107));
        jLabel21.setText("cm");

        jComboBoxBrojObuce.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxBrojObuce.setForeground(new java.awt.Color(223, 181, 107));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxAktivan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxAnsambl, 0, 235, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxBrojObuce, 0, 235, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxDan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxMesec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxGodina1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxMesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxGodina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxVisina, 0, 235, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxPol, 0, 235, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlabErrorPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlaberrorIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtBrojCK, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtBrojCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlaberrorIme, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabErrorPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxVisina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxDan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMesec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGodina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxBrojObuce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxAnsambl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxAktivan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 450, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(211, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
       
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        
        
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnEnableChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnableChangesActionPerformed
        
    }//GEN-LAST:event_jBtnEnableChangesActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnUbaciNovogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUbaciNovogActionPerformed
        
    }//GEN-LAST:event_jBtnUbaciNovogActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnEnableChanges;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnUbaciNovog;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JComboBox<String> jComboBoxAktivan;
    private javax.swing.JComboBox<domain.enumeracije.Ansambl> jComboBoxAnsambl;
    private javax.swing.JComboBox<Double> jComboBoxBrojObuce;
    private javax.swing.JComboBox<String> jComboBoxDan;
    private javax.swing.JComboBox<String> jComboBoxDan1;
    private javax.swing.JComboBox<String> jComboBoxGodina;
    private javax.swing.JComboBox<String> jComboBoxGodina1;
    private javax.swing.JComboBox<String> jComboBoxMesec;
    private javax.swing.JComboBox<String> jComboBoxMesec1;
    private javax.swing.JComboBox<domain.enumeracije.Pol> jComboBoxPol;
    private javax.swing.JComboBox<Double> jComboBoxVisina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxtBrojCK;
    private javax.swing.JTextField jTxtIme;
    private javax.swing.JTextField jTxtPrezime;
    private javax.swing.JLabel jlabErrorPrezime;
    private javax.swing.JLabel jlaberrorIme;
    // End of variables declaration//GEN-END:variables

    public void addButtonSaveListener(ActionListener ae){
        jBtnSave.addActionListener(ae);
    }
    
    public void addButtonUpdateListener(ActionListener ae){
        jBtnUpdate.addActionListener(ae);
    }
    public void addButtonDeleteListener(ActionListener ae){
        jBtnDelete.addActionListener(ae);
    }
    
    public void addButtonEnableChangesListener(ActionListener ae){
        jBtnEnableChanges.addActionListener(ae);
    }
    
    public void addButtonUbaciNovogListener(ActionListener ae){
        jBtnUbaciNovog.addActionListener(ae);
    }
    
    public void addButtonCancelListener(ActionListener ae){
        jBtnCancel.addActionListener(ae);
    }

    public javax.swing.JComboBox<String> getjComboBoxAktivan() {
        return jComboBoxAktivan;
    }

    public void setjComboBoxAktivan(javax.swing.JComboBox<String> jComboBoxAktivan) {
        this.jComboBoxAktivan = jComboBoxAktivan;
    }

    public javax.swing.JComboBox<domain.enumeracije.Ansambl> getjComboBoxAnsambl() {
        return jComboBoxAnsambl;
    }

    public void setjComboBoxAnsambl(javax.swing.JComboBox<domain.enumeracije.Ansambl> jComboBoxAnsambl) {
        this.jComboBoxAnsambl = jComboBoxAnsambl;
    }

    public javax.swing.JComboBox<Double> getjComboBoxBrojObuce() {
        return jComboBoxBrojObuce;
    }

    public void setjComboBoxBrojObuce(javax.swing.JComboBox<Double> jComboBoxBrojObuce) {
        this.jComboBoxBrojObuce = jComboBoxBrojObuce;
    }

    public javax.swing.JComboBox<String> getjComboBoxDan() {
        return jComboBoxDan;
    }

    public void setjComboBoxDan(javax.swing.JComboBox<String> jComboBoxDan) {
        this.jComboBoxDan = jComboBoxDan;
    }

    public javax.swing.JComboBox<String> getjComboBoxDan1() {
        return jComboBoxDan1;
    }

    public void setjComboBoxDan1(javax.swing.JComboBox<String> jComboBoxDan1) {
        this.jComboBoxDan1 = jComboBoxDan1;
    }

    public javax.swing.JComboBox<String> getjComboBoxGodina() {
        return jComboBoxGodina;
    }

    public void setjComboBoxGodina(javax.swing.JComboBox<String> jComboBoxGodina) {
        this.jComboBoxGodina = jComboBoxGodina;
    }

    public javax.swing.JComboBox<String> getjComboBoxGodina1() {
        return jComboBoxGodina1;
    }

    public void setjComboBoxGodina1(javax.swing.JComboBox<String> jComboBoxGodina1) {
        this.jComboBoxGodina1 = jComboBoxGodina1;
    }

    public javax.swing.JComboBox<String> getjComboBoxMesec() {
        return jComboBoxMesec;
    }

    public void setjComboBoxMesec(javax.swing.JComboBox<String> jComboBoxMesec) {
        this.jComboBoxMesec = jComboBoxMesec;
    }

    public javax.swing.JComboBox<String> getjComboBoxMesec1() {
        return jComboBoxMesec1;
    }

    public void setjComboBoxMesec1(javax.swing.JComboBox<String> jComboBoxMesec1) {
        this.jComboBoxMesec1 = jComboBoxMesec1;
    }

    public javax.swing.JComboBox<domain.enumeracije.Pol> getjComboBoxPol() {
        return jComboBoxPol;
    }

    public void setjComboBoxPol(javax.swing.JComboBox<domain.enumeracije.Pol> jComboBoxPol) {
        this.jComboBoxPol = jComboBoxPol;
    }

    public javax.swing.JComboBox<Double> getjComboBoxVisina() {
        return jComboBoxVisina;
    }

    public void setjComboBoxVisina(javax.swing.JComboBox<Double> jComboBoxVisina) {
        this.jComboBoxVisina = jComboBoxVisina;
    }

    public javax.swing.JTextField getjTxtBrojCK() {
        return jTxtBrojCK;
    }

    public void setjTxtBrojCK(javax.swing.JTextField jTxtBrojCK) {
        this.jTxtBrojCK = jTxtBrojCK;
    }

    public javax.swing.JTextField getjTxtIme() {
        return jTxtIme;
    }

    public void setjTxtIme(javax.swing.JTextField jTxtIme) {
        this.jTxtIme = jTxtIme;
    }

    public javax.swing.JTextField getjTxtPrezime() {
        return jTxtPrezime;
    }

    public void setjTxtPrezime(javax.swing.JTextField jTxtPrezime) {
        this.jTxtPrezime = jTxtPrezime;
    }

    public javax.swing.JButton getjBtnCancel() {
        return jBtnCancel;
    }

    public void setjBtnCancel(javax.swing.JButton jBtnCancel) {
        this.jBtnCancel = jBtnCancel;
    }

    public javax.swing.JButton getjBtnDelete() {
        return jBtnDelete;
    }

    public void setjBtnDelete(javax.swing.JButton jBtnDelete) {
        this.jBtnDelete = jBtnDelete;
    }

    public javax.swing.JButton getjBtnEnableChanges() {
        return jBtnEnableChanges;
    }

    public void setjBtnEnableChanges(javax.swing.JButton jBtnEnableChanges) {
        this.jBtnEnableChanges = jBtnEnableChanges;
    }

    public javax.swing.JButton getjBtnSave() {
        return jBtnSave;
    }

    public void setjBtnSave(javax.swing.JButton jBtnSave) {
        this.jBtnSave = jBtnSave;
    }

    public javax.swing.JButton getjBtnUbaciNovog() {
        return jBtnUbaciNovog;
    }

    public void setjBtnUbaciNovog(javax.swing.JButton jBtnUbaciNovog) {
        this.jBtnUbaciNovog = jBtnUbaciNovog;
    }

    public javax.swing.JButton getjBtnUpdate() {
        return jBtnUpdate;
    }

    public void setjBtnUpdate(javax.swing.JButton jBtnUpdate) {
        this.jBtnUpdate = jBtnUpdate;
    }

    public javax.swing.JLabel getJlabErrorPrezime() {
        return jlabErrorPrezime;
    }

    public void setJlabErrorPrezime(javax.swing.JLabel jlabErrorPrezime) {
        this.jlabErrorPrezime = jlabErrorPrezime;
    }

    public javax.swing.JLabel getJlaberrorIme() {
        return jlaberrorIme;
    }

    public void setJlaberrorIme(javax.swing.JLabel jlaberrorIme) {
        this.jlaberrorIme = jlaberrorIme;
    }
   
    
    
    
    
}
