/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;


import domain.Clan;
import domain.enumeracije.FormMode;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import ui.component.table.model.ClanTableModel;

/**
 *
 * @author Nemanja
 */
public class FPretragaClana extends javax.swing.JDialog {

    /**
     * Creates new form FPretragaClana
     */
    public FPretragaClana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        jTblClanovi.getTableHeader().setBackground(new Color(51,51,51));
        jTblClanovi.getTableHeader().setForeground(new Color(223,197,107));
        jScrollPane1.setBackground(new Color(51, 51, 51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblClanovi = new javax.swing.JTable();
        jBtnDetails = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTxtPretraga = new javax.swing.JTextField();
        jbtnPretrazi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(223, 197, 107));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(223, 197, 107));

        jTblClanovi.setAutoCreateRowSorter(true);
        jTblClanovi.setBackground(new java.awt.Color(51, 51, 51));
        jTblClanovi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N
        jTblClanovi.setForeground(new java.awt.Color(223, 197, 107));
        jTblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblClanovi.setGridColor(new java.awt.Color(51, 51, 51));
        jTblClanovi.setOpaque(false);
        jTblClanovi.setRowHeight(25);
        jTblClanovi.setSelectionBackground(new java.awt.Color(223, 197, 107));
        jTblClanovi.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jTblClanovi.setShowHorizontalLines(false);
        jTblClanovi.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTblClanovi);

        jBtnDetails.setBackground(new java.awt.Color(51, 51, 51));
        jBtnDetails.setForeground(new java.awt.Color(223, 200, 77));
        jBtnDetails.setText("Detalji");
        jBtnDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 200, 77), 1, true));
        jBtnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDetailsActionPerformed(evt);
            }
        });

        jBtnCancel.setBackground(new java.awt.Color(223, 200, 77));
        jBtnCancel.setForeground(new java.awt.Color(51, 51, 51));
        jBtnCancel.setText("Izađi");
        jBtnCancel.setBorder(null);
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretraga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(223, 197, 107))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(223, 197, 107));

        jTxtPretraga.setBackground(new java.awt.Color(51, 51, 51));
        jTxtPretraga.setForeground(new java.awt.Color(223, 200, 77));
        jTxtPretraga.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtnPretrazi.setBackground(new java.awt.Color(223, 200, 77));
        jbtnPretrazi.setForeground(new java.awt.Color(51, 51, 51));
        jbtnPretrazi.setText("Pretraži");
        jbtnPretrazi.setBorder(null);

        jLabel2.setForeground(new java.awt.Color(223, 197, 107));
        jLabel2.setText("Sifra:");

        jLabel3.setForeground(new java.awt.Color(223, 197, 107));
        jLabel3.setText("Ime:");

        jtxtIme.setBackground(new java.awt.Color(51, 51, 51));
        jtxtIme.setForeground(new java.awt.Color(223, 200, 77));
        jtxtIme.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setForeground(new java.awt.Color(223, 197, 107));
        jLabel4.setText("Prezime:");

        jtxtPrezime.setBackground(new java.awt.Color(51, 51, 51));
        jtxtPrezime.setForeground(new java.awt.Color(223, 200, 77));
        jtxtPrezime.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtPretraga))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtIme))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jBtnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDetailsActionPerformed
       
    }//GEN-LAST:event_jBtnDetailsActionPerformed

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnDetails;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblClanovi;
    private javax.swing.JTextField jTxtPretraga;
    private javax.swing.JButton jbtnPretrazi;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtPrezime;
    // End of variables declaration//GEN-END:variables

    

    public javax.swing.JButton getjBtnDetails() {
        return jBtnDetails;
    }

    public void setjBtnDetails(javax.swing.JButton jBtnDetails) {
        this.jBtnDetails = jBtnDetails;
    }

    public javax.swing.JTable getjTblClanovi() {
        return jTblClanovi;
    }

    public void setjTblClanovi(javax.swing.JTable jTblClanovi) {
        this.jTblClanovi = jTblClanovi;
    }

    public void addButtonDetailsListener(ActionListener ae){
        jBtnDetails.addActionListener(ae);
    }
    
    public void addButtonPretraziListener(ActionListener ae){
        jbtnPretrazi.addActionListener(ae);
    }

    public javax.swing.JButton getJbtnPretrazi() {
        return jbtnPretrazi;
    }

    public void setJbtnPretrazi(javax.swing.JButton jbtnPretrazi) {
        this.jbtnPretrazi = jbtnPretrazi;
    }

    public javax.swing.JTextField getjTxtPretraga() {
        return jTxtPretraga;
    }

    public void setjTxtPretraga(javax.swing.JTextField jTxtPretraga) {
        this.jTxtPretraga = jTxtPretraga;
    }

    public javax.swing.JTextField getJtxtIme() {
        return jtxtIme;
    }

    public void setJtxtIme(javax.swing.JTextField jtxtIme) {
        this.jtxtIme = jtxtIme;
    }

    public javax.swing.JTextField getJtxtPrezime() {
        return jtxtPrezime;
    }

    public void setJtxtPrezime(javax.swing.JTextField jtxtPrezime) {
        this.jtxtPrezime = jtxtPrezime;
    }
    
    
    
}
